### ISSUE TITLE
Bug: element is not a object

### ISSUE THREAD

**Issue by P72B** [OptimumCode/json-schema-validator#124]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Setup: KMP project that includes json-schema-validator lib.
JsonSchema.validate doesn't work on JS lib export. The kotlin unit test inside the kmp project works and the schema gets validated correctly. But when I take the generated JS lib output (gradle jsRun) from the kmp then I get an errror during NodeJS runtime schema validation attempt with the message "`element is not a object`".

### Expected Behavior

It should be validating same json schema on kotlin as well as on nodejs platform.

### JSON schema

```json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://example.com/product.schema.json",
  "title": "Product",
  "description": "A product from Acme's catalog",
  "type": "object",
  "properties": {
    "productId": {
      "description": "The unique identifier for a product",
      "type": "integer"
    },
    "productName": {
      "description": "Name of the product",
      "type": "string"
    },
    "price": {
      "description": "The price of the product",
      "type": "number",
      "exclusiveMinimum": 0
    }
  },
  "required": [ "productId", "productName", "price" ]
}
```

### Library version

0.0.15

### Anything else?

<img width="482" alt="kmp code" src="https://github.com/OptimumCode/json-schema-validator/assets/2487501/34709be7-a35e-464e-97d5-ee4d148080c4">
<img width="587" alt="kmp unit test" src="https://github.com/OptimumCode/json-schema-validator/assets/2487501/173750ad-6cc9-43b5-9907-f3053ea88bec">
<img width="550" alt="nodejs code implementing JS kmp lib" src="https://github.com/OptimumCode/json-schema-validator/assets/2487501/f13fab24-717b-47a6-8a51-3a1894367e9a">
<img width="254" alt="Error message" src="https://github.com/OptimumCode/json-schema-validator/assets/2487501/4b161018-7554-42e5-9aff-8262a6a65bef">

**Comment by OptimumCode** [comment]
Hi, @P72B. Thank you for reporting this issue.

Could you share a minimum project so I can reproduce the issue locally?
And what does `req.body` return in JS? Are you sure it returns `JsonElement`? I have not worked with JS for a long time, probably, you probably need first to deserialize the request payload using kotlin-serialization library in JS and only then pass it to the validation function

**Comment by P72B** [comment]
Invalid bug report

**Comment by OptimumCode** [comment]
No worries, was happy to help) And I am glad that somebody uses the library)
