### ISSUE TITLE
Enhancement: Add new `wasm` target

### ISSUE THREAD

**Issue by mikepenz** [OptimumCode/json-schema-validator#177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Thank you very much for your great work on this library. You already have quite a long list of supported targets. 

https://github.com/OptimumCode/json-schema-validator?tab=readme-ov-file#supported-targets

However would it be possible to expand the list by the `wasm` target?

https://kotlinlang.org/docs/wasm-overview.html

**Comment by mikepenz** [comment]
Just noticed that this might be blocked by https://github.com/Doist/doistx-normalize not offering a `wasm` yet

**Comment by OptimumCode** [comment]
Hi, @mikepenz. Thank you for your interest in this library!

I was also thinking about adding support for `wasm` target but as you noticed it depends on other libraries.
If I find time I will try to make PRs with `wasm` support to those libraries you mentioned. But for now, unfortunately, I am quite busy with other work...

Added this task into the backlog.

**Comment by mikepenz** [comment]
I actually looked to do exactly that :D. Wanted to open a wasm PR on the normalize lib, but the resource lib it depends on blocks this. 

(Otherwise I would also have opened a PR on your library expanding wasm support) 

One question. How strongly do you need the `normalize` dependency? Would it be fine to have wasm support without normalize support? 🤔

**Comment by OptimumCode** [comment]
> How strongly do you need the normalize dependency? Would it be fine to have wasm support without normalize support? 🤔

This library is required to support `idn-hostname` format (the string normalization is part of the [specification](https://www.rfc-editor.org/rfc/inline-errata/rfc5890.html) for this format). Some additional information can be found in [readme](https://github.com/OptimumCode/json-schema-validator?tab=readme-ov-file#build-process).

Probably, I could exclude normalization from `wasm` target but in this case, the `idn-hostname` format will be broken...

How strongly do you need the wasm support? I think if this is quite urgent for some of your projects I could do what is described above (there is no major release yet, so, it is probably okay to release something that works a bit differently on wasm target...)

It will require transforming `io.github.optimumcode.json.schema.internal.hostname.Normalizer` into expect/actual object and creating a dummy implementation for `wasm` that always returns `true`. And also some tests should be excluded for `wasm` target after that.

**Comment by mikepenz** [comment]
@OptimumCode thank you for taking the time to provide the details on the `idn-hostname`.
This wouldn't be something I would need, however I do understand that this will make `wasm` a less complete target as the others. 

If you are ok with it, I can spend some time to open a PR with the outlined proposal. I'd leave it up to you if you want to have it then as part of the library already, or if you (if possible) maybe wanna do a `-wasm0` special release version like what other projects did while wasm wasn't on par with other targets.

**Comment by OptimumCode** [comment]
> if you (if possible) maybe wanna do a -wasm0 special release version like what other projects did while wasm wasn't on par with other targets.

Could you please share an example of such a project (if you know any)? I would prefer this option to separate incomplete `wasm` implementation from others

> If you are ok with it, I can spend some time to open a PR with the outlined proposal.

I would much appreciate this) However, I am not sure when I find time to review the changes (will try to do that as soon as possible)

**Comment by mikepenz** [comment]
I know [ktor](https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental/io/ktor/ktor-client-auth-wasm/) had some releases which were on a different branch for a while. Similar [supabase-kt](https://github.com/supabase-community/supabase-kt/releases/tag/2.5.4-wasm0) has some releases which are different for wasm.
Or in other words releases which are from a different branch with an individual naming scheme to indicate that it's not default. 

And yes I will have a look :). And don't worry about how quick you may be able to review, I fully understand it sometimes taking more time! Really appreciate your work here!
