### ISSUE TITLE
Too much validation errors

### ISSUE THREAD

**Issue by OussemaHammami** [OptimumCode/json-schema-validator#47]
I faced an issue when using this library. 
I have an object named "type" marked as required. When it didn't appear in the JSON object to be validated i am expecting only an error mentioning the missing object. But, in addition to this error,  some other errors related to conditions from the block of "allOf" based on the missing object("type") are also thrown also. It is supposed to return only the error of the missing object "type". 

My JSON schema: 

``` 
"title": "resource",
  "type": "object",
  "required": [
    "type"
  ],
  ...
  
  "allOf": [
    {
      "if": {
        "properties": {
          "type": {
            "enum": [
              "enum1",
              "enum2"
            ]
          }
        }
      },
      "then": {
        "properties": {
          "host": {
            "properties": {
		.
		.
		.
              }
            }
          }
        },
        "required": [
          "host"
        ]
      }
    },
    {
      "if": {
        "properties": {
          "type": {
            "enum": [
              "enum1",
              "enum2",
              "enum3",
              "enum4",
            ]
          }
        }
      },
      "then": {
        "required": [
          "amount"
        ]
      }
    },
    {
      "if": {
        "properties": {
          "type": {
            "enum": [
              "enum5"
            ]
          }
        }
      },
      "then": {
        "properties": {
		.
		.
		.
        },
        "required": [
          "payment_type"
        ]
      }
    }
  ]
```
json to be validated: 
```
"resource": {}
```

Returned errors: 

- missing required properties: [host]
- missing required properties: [payment_type]
- missing required properties: [type]

I think it is supposed to return :

- missing required properties: [type]

**Comment by OptimumCode** [comment]
Hi, @OussemaHammami.
Thank you for raising this to me and sorry for the inconvenience. I will check this as soon as possible

**Comment by OptimumCode** [comment]
Closing this issue as the library behavior matches the JSON specification.
@OussemaHammami if you have any more question about the library don't hesitate to ask by creating a new issue
