### ISSUE TITLE
Enhancement: Support $defs subschemas in Json

### ISSUE THREAD

**Issue by jrhok** [OptimumCode/json-schema-validator#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Enhancement description

Hello,

According to the [official documentation of JSON Schema](https://json-schema.org/understanding-json-schema/structuring#defs) , the standardized place to put subschemas should be "$defs", it is not currently supported by the library (it seems to only support "definitions" section)

**Comment by jrhok** [comment]
Oh ! Sorry, I did not notice that draft 7 did not support $defs, thank you, I close the issue

**Comment by OptimumCode** [comment]
No worries, you are welcome)
The `$defs` keyword was added in the draft 2019-09. This is why the library does not support this keyword for drafts before 2019-09.
Also, I would suggest using the latest draft (2020-12) as it is better in some ways than the older drafts (if it is possible in your case of course)
